15/8/22

diff --git a/bin/tmuxinator-start b/bin/tmuxinator-start
--- a/bin/tmuxinator-start
+++ b/bin/tmuxinator-start
@@ -1,11 +1,23 @@
 #!/bin/sh
 
-if ! test -f "$2/$3"; then
-    echo "project does not exists"
+if ! test -z "$1"; then
+    selected="$1"
+else
+    selected=$(find $PERSONAL_PROJECTS $WORK_PROJECTS -mindepth 1 -maxdepth 1 -type d | fzf)
+fi
+if test -z "$selected" ; then
     exit 1
 fi
 
-tmuxinator start \
-    --project-config="$2/$3" \
-    project="$1" \
-    workspace="$2"
+selected_name=$(basename "$selected")
+#selected_name=$(basename "$selected" | tr . _)
+
+if test -f "$selected/.tmuxinator.yml"; then
+    tmuxinator start \
+        --project-config="$selected/.tmuxinator.yml" \
+        project="$selected_name" \
+        workspace="$selected"
+else
+    echo "tmuxinator session not found"
+    exit 1
+fi
